### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by kawapiki** [dkurt/openvino_demo#2]
Hi, i wanted to test your great project, but i cant even compile it with new openvino api.

log:
/opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/samples/openvino_demo/main.cpp: In function \u2018int main(int, char**)\u2019:
/opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/samples/openvino_demo/main.cpp:319:5: error: converting to \u2018std::tuple<char*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double>\u2019 from initializer list would use explicit constructor \u2018constexpr std::tuple< <template-parameter-1-1> >::tuple(const _Elements& ...) [with _Elements = {char*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double}]\u2019
     };
     ^
/opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/samples/openvino_demo/main.cpp:319:5: warning: deprecated conversion from string constant to \u2018char*\u2019 [-Wwrite-strings]
/opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/samples/openvino_demo/main.cpp:319:5: error: converting to \u2018std::tuple<char*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double>\u2019 from initializer list would use explicit constructor \u2018constexpr std::tuple< <template-parameter-1-1> >::tuple(const _Elements& ...) [with _Elements = {char*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double}]\u2019
/opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/samples/openvino_demo/main.cpp:319:5: warning: deprecated conversion from string constant to \u2018char*\u2019 [-Wwrite-strings]
/opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/samples/openvino_demo/main.cpp:319:5: error: converting to \u2018std::tuple<char*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double>\u2019 from initializer list would use explicit constructor \u2018constexpr std::tuple< <template-parameter-1-1> >::tuple(const _Elements& ...) [with _Elements = {char*, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, double}]\u2019
/opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/samples/openvino_demo/main.cpp:319:5: warning: deprecated conversion from string constant to \u2018char*\u2019 [-Wwrite-strings]
/opt/intel/openvino_2019.1.133/deployment_tools/inference_engine/samples/openvino_demo/main.cpp:323:80: error: cannot pass objects of non-trivially-copyable type \u2018const class std::basic_string<char>\u2019 through \u2018...\u2019
                                      std::get<1>(data), 1.0 / std::get<2>(data));
                                                                                ^
make[2]: *** [CMakeFiles/demo.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/demo.dir/all] Error 2
make: *** [all] Error 2

**Comment by Jerry3062** [comment]
Hi,i add "set(OpenCV_DIR /opt/intel/openvino_2019.1.144/opencv/cmake)" this before "find_package(OpenCV REQUIRED)" and solve this problem.
